

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    maxIdle: 10
    maxTotal: 300
    maxWait: 10000
    testOnBorrow: true
    timeout: 100000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

redis:
  limit: 10

